# Generated by Django 4.1.4 on 2023-01-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campuses',
                'db_table': 'campus',
            },
        ),
    ]
