# Generated by Django 4.1.4 on 2023-01-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
