# Generated by Django 4.1.4 on 2023-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='department', max_length=20),
            preserve_default=False,
        ),
    ]
