# Generated by Django 4.1.4 on 2023-01-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('information technology', 'information technology'), ('computer engineering', 'computer engineering'), ('civil engineering', 'civil engineering'), ('mechanical engineering', 'mechanical engineering')], max_length=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='campus.campus')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'department',
            },
        ),
    ]
